Solvable synthesis
probing-lab/polar pull request #19
Opened 2023-05-08 14:48 UTC by daneshvar-amrollahi

Added a new action for synthesizing solvable loops by replacing the defective variables with a fresh variable (if possible). The returned output is a list of solvable programs. 

How to Test:

`python polar.py benchmarks/defective/non-lin-markov-1.prob --synth_solv 2`
`python polar.py benchmarks/defective/squares.prob --synth_solv 1`

The parameter passed to `--synth_solv` is the degree of the invariant (combination) used for the search. 

You may add also add the simultaneous assignment, `n = n + 1, m + 2`  to squares.prob.

2023-05-15 09:04 UTC, mmsbrggr commented on cli/argument_parser.py
> +        self.argument_parser.add_argument(
use mc_comb_deg

2023-05-15 09:07 UTC, mmsbrggr commented on cli/argument_parser.py
> +        self.argument_parser.add_argument(
--synth_solv [optional:list of vars]

2023-05-15 09:14 UTC, mmsbrggr commented on program/solvable_synthesizer/solvable_synthesizer.py
> +from utils import get_unique_var, solve_rec_by_summing, get_terms_with_vars, get_monoms
please use mc_comb_finder -> avoid code duplication

2023-05-15 13:37 UTC, mmsbrggr commented on cli/actions/synthesize_solvable_action.py
> +                solvable_loop_body = []
Could you move the construction of the program to the SolvableSynthesizer? The CLI actions should do as minimal logic as possible. Doing so we can use the synthesizer in other contexts in the future (without CLI)

2023-05-15 13:39 UTC, mmsbrggr requested changes
Functionality is fine. Could you please incorporate the changes mentioned in the comments?

2023-05-18 07:49 UTC, daneshvar-amrollahi commented
Fixed bugs with effective variables. 

Input 1:
```
while true:
    x = x + 1
    y = y + x
    z = z**2
end
```
Output 1:
```
while true:
    _t4 = 1 + x
    _t5 = 1 + x + y
    x = _t4
    y = _t5
end

Sample 2:
```
while true:
    s = Bernoulli(1/2)
    if s == 0:
        x, y = x + x*y, (1/3)*x + (2/3)*y + (x*y)
    else:
        x, y = x + y + (2/3)*x*y, 2*y + (2/3)*(x*y)
    end
    z = z**2
    m = m + 1
    n = m + 2
end
```
Output 2:
```
while true:
    _t16 = 1/2
    _s15 = (13/18)*_s15
    _t17 = 1 + m
    _t18 = 3 + m
    s = _t16
    m = _t17
    n = _t18
end
```

2023-05-22 12:25 UTC, mmsbrggr commented on cli/actions/synthesize_solvable_action.py
> +        if len(program.non_mc_variables) == 0:
Should also work with solvable loops

2023-05-22 13:30 UTC, merged